# Generated by Django 4.2.7 on 2024-09-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('best_aspirations', models.ManyToManyField(to='core.aspiration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(max_length=250)),
                ('positivity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.career')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='career',
            name='best_traits',
            field=models.ManyToManyField(to='core.trait'),
        ),
        migrations.AddField(
            model_name='aspiration',
            name='bonus_trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_trait_set', to='core.trait'),
        ),
        migrations.AddField(
            model_name='aspiration',
            name='reward_trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_trait_set', to='core.trait'),
        ),
    ]
