# Generated by Django 4.2.7 on 2024-08-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='traits',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
